todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import todo_app.views
from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("todo-app/", include("todo_app.urls", namespace="todo-app")),
    path('', todo_app.views.landPage, name='land-page'),
    path('login/', todo_app.views.loginPage, name='login'),
    path('logout/', todo_app.views.logoutPage, name='logout'),
    path('signup/', todo_app.views.signupPage, name='signup'),
    path('password-reset/', PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_app/urls.py
from django.urls import path

from .views import homePage, detailPage, createPage, updatePage, deletePage

app_name = "todo_app"

urlpatterns = [
    path('', homePage, name="home-page"),
    path('create/', createPage, name="create-page"),
    path('task/<int:pk>/', detailPage, name="detail-page"),
    path('update/<int:pk>/', updatePage, name="update-page"),
    path('delete/<int:pk>/', deletePage, name="delete-page"),
]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=25)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-is_completed']
    
    def __str__(self):
        return self.title

todo_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Task

class TaskCreateForm(ModelForm):
    class Meta:
        model = Task
        # fields = '__all__'
        exclude = ["user", "is_completed", 'updated',]
        
class TaskUpdateForm(ModelForm):
    class Meta:
        model = Task
        # fields = '__all__'
        exclude = ["user",]
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)
    
class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Input a valid email address.')
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

todo_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Task
from .forms import TaskCreateForm, LoginForm, TaskUpdateForm, SignupForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404
from django.core.mail import send_mail
# Create your views here.

def landPage(request):
    return render(request, 'todo_app/landpage.html')

@login_required
def homePage(request):
    q = request.GET.get('q', None)
    if q is None or q is "":
        tasks = Task.objects.filter(user=request.user)
    elif q is not None:
        tasks = Task.objects.filter(user=request.user, title__icontains=q)
    count = Task.objects.filter(user=request.user, is_completed=False).count()
    return render(request, 'todo_app/homepage.html', {'tasks':tasks, 'count':count})

@login_required
def detailPage(request, pk):
    task = get_object_or_404(Task, id=pk)
    return render(request, 'todo_app/detail_page.html', {'task':task})

@login_required
def createPage(request):
    form = TaskCreateForm()
    if request.method == 'POST':
        form = TaskCreateForm(request.POST, request.FILES)
        if form.is_valid():
            # form = Task(user=request.user)
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            # return redirect(reverse(('todo-app:home-page')))                                                                                                                                                                                                                                                                                                           
            return redirect('todo-app:home-page')
    return render(request, 'todo_app/create_page.html', {'form':form})

@login_required
def updatePage(request, pk):
    task = get_object_or_404(Task, id=pk)
    if task.user != request.user:
        raise Http404
    form = TaskUpdateForm(instance=task)
    if request.method == 'POST':
        form = TaskUpdateForm(request.POST, request.FILES, instance=task)
        if form.is_valid():
            # form = Task(user=request.user)
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            # return redirect(reverse(('todo-app:home-page')))
            return redirect('todo-app:home-page')                                                                                                                                                                                                                                                                                                           
    return render(request, 'todo_app/update_page.html', {'form':form})

@login_required
def deletePage(request, pk):
    task = get_object_or_404(Task, id=pk)
    if task.user != request.user:
        raise Http404
    if request.method == 'POST':
        task.delete()
        return redirect('todo-app:home-page')
    return render(request, 'todo_app/delete_page.html', {'task':task})

def loginPage(request):
    form = LoginForm()
    message = ''
    if request.user.is_authenticated:
        return redirect('todo-app:home-page')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'],)
            if user is not None:
                login(request, user)
                message = f'Hello {user.username}! You have been logged in'
                return redirect('land-page')
            else:
                message = 'User does not exist, check your credentials!.'
    return render(
        request, 'todo_app/login.html', {'form': form, 'message': message})

def logoutPage(request):
    logout(request)
    return redirect('login')

def signupPage(request):
    form = SignupForm()
    if request.user.is_authenticated:
        return redirect('todo-app:home-page')
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password = raw_password)
            # login(request, user)
            return redirect('login')
    return render(request, 'todo_app/signup.html', {'form':form})

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

todo_app/templates/todo_app/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% tailwind_css %}
    <link
      href="https://fonts.googleapis.com/css2?family=Comme:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>{% block title %}Welcome{% endblock %} | DJTodo</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="max-h-screen bg-[#ecded3]">
    <div class="max-w-4xl p-6 px-6 mx-auto mt-4">
      <div class="mb-4">
        {% if user.is_authenticated %}
        <p>
          You're logged in as
          <em class="text-xl font-bold">{{request.user}}</em>. Click here to
          <a
            class="inline-flex text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg"
            href="{% url 'logout' %}"
            >Logout</a
          >
        </p>

        {% endif %}
      </div>
      {% block content %} {% endblock %}
      <footer class="text-center font-bold text-black">
        &copy;<a href="https://github.com/Abdulmumin3/DJTodoApp"
          >abdulwale(anonymous)</a
        >
      </footer>
    </div>
  </body>
</html>

todo_app/templates/todo_app/create_page.html
{% extends "todo_app/base.html" %}
<!--  -->
{% block title %}Create{% endblock %}
<!--  -->

{% block content %}
<a class="font-bold" href="{% url 'todo-app:home-page' %}">&larr;Go back to Tasks</a>
<h2 class="mt-4 text-2xl font-bold mb-4">Create Task</h2>
<form method="POST" action="">
  {% csrf_token %}
<!--  {{form.as_p}}-->
  {% for field in form %}
  <p class="text-xl font-bold">
    {{ field.label_tag }}<br>
    {{ field }}
    {% if field.help_text %}
        <small style="color: gray">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
    {% endfor %}
  </p>
  {% endfor %}
  <input type="submit" value="Create" class="mt-6 inline-flex text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg" />
</form>
{% endblock %}

todo_app/templates/todo_app/delete_page.html
{% extends "todo_app/base.html" %}
<!--  -->
{% block title %}Delete Task{{task.id}}{% endblock %}
<!--  -->
{% block content %}
<a class="text-xl font-bold" href="{% url 'todo-app:home-page' %}">&larr;Go back to Tasks</a>
<h2 class="text-2xl mt-4 font-bold mb-4 text-black">Delete Task <strong>"{{task}}"</strong></h2>
<form method="POST" action="">
  {% csrf_token %}
  <p>Are you sure you want to delete <strong>"{{task}}"</strong>?</p>
  <a href="{{request.META.HTTP_REFERER}}">&larr; Go back</a>
  <input
    type="submit"
    value="Confirm"
    class="inline-flex mb-4 mt-4 text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg"
  />
</form>
{% endblock %}

todo_app/templates/todo_app/detail_page.html
{% extends "todo_app/base.html" %}
<!--  -->
{% block title %}Task{{task.id}}{% endblock %}
<!--  -->
{% block content %}
<a href="{% url 'todo-app:home-page' %}">&larr; Go back to Tasks</a>
<div class="flex mb-4 mt-4 justify-between items-center">
  <h3 class="font-bold">Task: {{task}}</h3>
  <h3>{{task.updated}}</h3>
</div>
<p class="mb-8"><strong>Description:</strong> {{task.description}}</p>
<p><strong>Status:</strong></p>
{% if task.is_completed %}
<p>Completed</p>
{% else %}
<p>Uncompleted</p>
{% endif %}
<div class="mt-6">
  <a
    class="inline-flex text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg"
    href="{% url 'todo-app:update-page' task.id %}"
    >Update task</a
  >
  <a
    class="inline-flex ml-4 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg"
    href="{% url 'todo-app:delete-page' task.id %}"
    >Delete task</a
  >
</div>
{% endblock %}

todo_app/templates/todo_app/homepage.html
{% extends "todo_app/base.html" %} {% block title %}Tasks{% endblock %}
<!--  -->
{% block content %}
<a href="{% url 'land-page' %}">&larr;Home</a>
<nav>
  <div class="flex justify-between items-center">
    <form action="" method="get">
      <input
        type="text"
        id="q"
        name="q"
        value="{{ request.GET.q }}"
        placeholder="Search tasks..."
        aria-label="Search"
        class="rounded"
      />
      <button
        class="mt-6 inline-flex text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg"
        type="submit"
      >
        Search
      </button>
    </form>
  </div>
</nav>
<h3 class="mt-4 mb-4 text-xl font-bold">
  You have <em>{{count}}</em> incomplete tasks
</h3>
<div class="flex mb-4 mt-4 font-bold text-2xl justify-between items-center">
  <h2>Tasks</h2>
  <a class="items-end" href="{% url 'todo-app:create-page' %}"
    >Create a new task</a
  >
</div>
<ul class="space-y-4">
  {% for task in tasks %}
  <div
    class="flex py-4 px-4 justify-between items-center shadow border border-solid"
  >
    <div>
      <li>
        <a class="text-xl" href="{% url 'todo-app:detail-page' task.pk %}"
          >{{task}}</a
        >
      </li>
    </div>
    <div>
      {% if task.is_completed %}
      <p>Completed</p>
      {% else %}
      <p>Uncompleted</p>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</ul>
{% endblock %}

todo_app/templates/todo_app/landpage.html
{% extends "todo_app/base.html" %} {% block title %}Landing-page{% endblock %}
<!--  -->
{% block content %}

<nav class="shadow px-4 py-4">
  <div class="flex items-center justify-between">
    <div class="text-2xl font-extrabold text-teal-700" id="logo">
      <em>DJTodo</em>
    </div>
    <div class="flex justify-between items-center md:space-x-12">
      {% if user.is_authenticated %}
      <a
        class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        href="{% url 'logout' %}"
        >Logout</a
      >
      <a
        class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        href="{% url 'todo-app:home-page' %}"
        >Tasks</a
      >
      <a
        class="inline-flex hidden md:block text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        href="{% url 'land-page' %}"
        >Home</a
      >

      {% else %}
      <a
        class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        href="{% url 'signup' %}"
        >Signup</a
      >
      <a
        class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        href="{% url 'login' %}"
        >Login</a
      >

      {% endif %}
    </div>
  </div>
</nav>
<div class="text-center mt-36">
  <h2 class="text-[40px] font-extrabold text-teal-700">DJTodo</h2>
  <p class="font-bold text-black-700"><em>managing your tasks...</em></p>
</div>

{% endblock %}

todo_app/templates/todo_app/login.html
{% extends "todo_app/base.html" %}
<!--  -->
{% block title %}Login{% endblock %}
<!--  -->
{% block content %}
<!-- <a href="{% url 'todo-app:home-page' %}"></a> -->
<div class="p-8 mx-auto items-center shadow-md rounded-md bg-gray">
<h2 class="text-2xl font bold">Login</h2>
{% if message %}
<p class="text-red">{{message}}</p>
{% endif %}
<form method="POST" action="">
  {% csrf_token %}
<!--  {{form.as_p}}-->
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
          <small style="color: gray">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <input type="submit" value="Login" class="inline-flex text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg  mt-4 mb-4" />
</form>
<h3 class="mb-4">Forgot Password? <a href="{%url 'password-reset'%}"><em class="text-xl font-bold">Reset Password</em></a></h3>
<h3>You don't have an account, <a class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"  href="{% url 'signup' %}">Signup</a></h3>
</div>
{% endblock %}

todo_app/templates/todo_app/signup.html
{% extends "todo_app/base.html" %}
<!--  -->
{% block title %}Signup{% endblock %}
<!--  -->
{% block content %}
<!-- <a href="{% url 'todo-app:home-page' %}"></a> -->

<h2>Signup</h2>
{% if message %}
<p>{{message}}</p>
{% endif %}
<form method="POST" action="">
  {% csrf_token %} 
  <!-- {{form.as_p}} -->
  {% for field in form %}
  <p>
    {{ field.label_tag }}<br>
    {{ field }}<br>
    {% if field.help_text %}
        <small style="color: gray">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
    {% endfor %}
  </p>
  {% endfor %}
  <input type="submit" value="Signup" class="inline-flex mt-4 mb-4 text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg" />
</form>
<h3>Already have an account, <a class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg" href="{% url 'login' %}">Login</a></h3>
{% endblock %}

todo_app/templates/todo_app/update_page.html
{% extends "todo_app/base.html" %}
<!--  -->
{% block title %}Update Task{{task.id}}{% endblock %}
<!--  -->
{% block content %}
<div class="mx-auto my-auto">
<a class="font-bold" href="{% url 'todo-app:home-page' %}">&larr; Go back to Tasks</a>
<h2 class="mt-4 mb-4 text-2xl font-bold">Update Task {{task}}</h2>
<form method="POST" action="">
  {% csrf_token %}
<!--  {{form.as_p}}-->
  {% for field in form %}
  <p>
    {{ field.label_tag }}<br>
    {{ field }}
    {% if field.help_text %}
        <small style="color: gray">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
    {% endfor %}
  </p>
  {% endfor %}
  <input type="submit" value="Update" class="mt-6 inline-flex text-white bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg" />
</form>
</div>
{% endblock %}